#!/usr/bin/env python3
"""
One-shot AI categorization. The category for each question (by its
index in questions.json) was assigned by Claude based on meaning,
not regex. Re-run this script to regenerate questions-to-review.md.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).parent
IN_FILE = HERE / "questions.json"
OUT_FILE = HERE / "questions-to-review.md"

CATEGORY_ORDER = [
    "Religion & Morality",
    "Family, Gender & Sexuality",
    "Environment & Climate",
    "Immigration & National Identity",
    "Foreign Policy & International Relations",
    "Justice, Crime & Law Enforcement",
    "Education",
    "Healthcare",
    "Technology, Media & Privacy",
    "Labor & Workers",
    "Economy & Markets",
    "Taxation & Welfare",
    "Government, Authority & State Power",
    "Democracy & Political System",
    "Civil Liberties & Individual Rights",
    "Society & Culture",
]

# Index in questions.json -> category. Assigned by Claude.
CATEGORY_BY_INDEX: dict[int, str] = {
    0: "Economy & Markets",
    1: "Economy & Markets",
    2: "Economy & Markets",
    3: "Taxation & Welfare",
    4: "Economy & Markets",
    5: "Foreign Policy & International Relations",
    6: "Economy & Markets",
    7: "Taxation & Welfare",
    8: "Taxation & Welfare",
    9: "Economy & Markets",
    10: "Economy & Markets",
    11: "Economy & Markets",
    12: "Healthcare",
    13: "Education",
    14: "Labor & Workers",
    15: "Foreign Policy & International Relations",
    16: "Foreign Policy & International Relations",
    17: "Foreign Policy & International Relations",
    18: "Foreign Policy & International Relations",
    19: "Foreign Policy & International Relations",
    20: "Foreign Policy & International Relations",
    21: "Foreign Policy & International Relations",
    22: "Foreign Policy & International Relations",
    23: "Foreign Policy & International Relations",
    24: "Immigration & National Identity",
    25: "Foreign Policy & International Relations",
    26: "Foreign Policy & International Relations",
    27: "Civil Liberties & Individual Rights",
    28: "Religion & Morality",
    29: "Immigration & National Identity",
    30: "Justice, Crime & Law Enforcement",
    31: "Democracy & Political System",
    32: "Healthcare",
    33: "Civil Liberties & Individual Rights",
    34: "Technology, Media & Privacy",
    35: "Government, Authority & State Power",
    36: "Immigration & National Identity",
    37: "Government, Authority & State Power",
    38: "Government, Authority & State Power",
    39: "Democracy & Political System",
    40: "Government, Authority & State Power",
    41: "Democracy & Political System",
    42: "Environment & Climate",
    43: "Technology, Media & Privacy",
    44: "Religion & Morality",
    45: "Society & Culture",
    46: "Religion & Morality",
    47: "Religion & Morality",
    48: "Environment & Climate",
    49: "Environment & Climate",
    50: "Society & Culture",
    51: "Society & Culture",
    52: "Society & Culture",
    53: "Society & Culture",
    54: "Justice, Crime & Law Enforcement",
    55: "Family, Gender & Sexuality",
    56: "Society & Culture",
    57: "Family, Gender & Sexuality",
    58: "Immigration & National Identity",
    59: "Family, Gender & Sexuality",
    60: "Justice, Crime & Law Enforcement",
    61: "Healthcare",
    62: "Justice, Crime & Law Enforcement",
    63: "Family, Gender & Sexuality",
    64: "Society & Culture",
    65: "Technology, Media & Privacy",
    66: "Immigration & National Identity",
    67: "Foreign Policy & International Relations",
    68: "Civil Liberties & Individual Rights",
    69: "Society & Culture",
    70: "Economy & Markets",
    71: "Taxation & Welfare",
    72: "Labor & Workers",
    73: "Society & Culture",
    74: "Labor & Workers",
    75: "Economy & Markets",
    76: "Taxation & Welfare",
    77: "Society & Culture",
    78: "Economy & Markets",
    79: "Taxation & Welfare",
    80: "Taxation & Welfare",
    81: "Economy & Markets",
    82: "Economy & Markets",
    83: "Society & Culture",
    84: "Economy & Markets",
    85: "Technology, Media & Privacy",
    86: "Government, Authority & State Power",
    87: "Government, Authority & State Power",
    88: "Government, Authority & State Power",
    89: "Government, Authority & State Power",
    90: "Technology, Media & Privacy",
    91: "Civil Liberties & Individual Rights",
    92: "Technology, Media & Privacy",
    93: "Government, Authority & State Power",
    94: "Democracy & Political System",
    95: "Justice, Crime & Law Enforcement",
    96: "Government, Authority & State Power",
    97: "Government, Authority & State Power",
    98: "Justice, Crime & Law Enforcement",
    99: "Education",
    100: "Civil Liberties & Individual Rights",
    101: "Civil Liberties & Individual Rights",
    102: "Religion & Morality",
    103: "Civil Liberties & Individual Rights",
    104: "Environment & Climate",
    105: "Family, Gender & Sexuality",
    106: "Society & Culture",
    107: "Civil Liberties & Individual Rights",
    108: "Family, Gender & Sexuality",
    109: "Family, Gender & Sexuality",
    110: "Justice, Crime & Law Enforcement",
    111: "Justice, Crime & Law Enforcement",
    112: "Justice, Crime & Law Enforcement",
    113: "Religion & Morality",
    114: "Family, Gender & Sexuality",
    115: "Immigration & National Identity",
    116: "Labor & Workers",
    117: "Government, Authority & State Power",
    118: "Government, Authority & State Power",
    119: "Democracy & Political System",
    120: "Economy & Markets",
    121: "Labor & Workers",
    122: "Government, Authority & State Power",
    123: "Taxation & Welfare",
    124: "Democracy & Political System",
    125: "Civil Liberties & Individual Rights",
    126: "Economy & Markets",
    127: "Economy & Markets",
    128: "Economy & Markets",
    129: "Economy & Markets",
    130: "Economy & Markets",
    131: "Economy & Markets",
    132: "Society & Culture",
    133: "Economy & Markets",
    134: "Society & Culture",
    135: "Economy & Markets",
    136: "Economy & Markets",
    137: "Economy & Markets",
    138: "Economy & Markets",
    139: "Economy & Markets",
    140: "Labor & Workers",
    141: "Government, Authority & State Power",
    142: "Economy & Markets",
    143: "Economy & Markets",
    144: "Government, Authority & State Power",
    145: "Labor & Workers",
    146: "Foreign Policy & International Relations",
    147: "Immigration & National Identity",
    148: "Democracy & Political System",
    149: "Foreign Policy & International Relations",
    150: "Immigration & National Identity",
    151: "Foreign Policy & International Relations",
    152: "Society & Culture",
    153: "Labor & Workers",
    154: "Foreign Policy & International Relations",
    155: "Foreign Policy & International Relations",
    156: "Democracy & Political System",
    157: "Labor & Workers",
    158: "Government, Authority & State Power",
    159: "Democracy & Political System",
    160: "Labor & Workers",
    161: "Society & Culture",
    162: "Democracy & Political System",
    163: "Government, Authority & State Power",
    164: "Labor & Workers",
    165: "Environment & Climate",
    166: "Environment & Climate",
    167: "Environment & Climate",
    168: "Environment & Climate",
    169: "Environment & Climate",
    170: "Environment & Climate",
    171: "Environment & Climate",
    172: "Environment & Climate",
    173: "Environment & Climate",
    174: "Environment & Climate",
    175: "Environment & Climate",
    176: "Environment & Climate",
    177: "Environment & Climate",
    178: "Family, Gender & Sexuality",
    179: "Family, Gender & Sexuality",
    180: "Family, Gender & Sexuality",
    181: "Family, Gender & Sexuality",
    182: "Religion & Morality",
    183: "Civil Liberties & Individual Rights",
    184: "Religion & Morality",
    185: "Justice, Crime & Law Enforcement",
    186: "Immigration & National Identity",
    187: "Society & Culture",
    188: "Government, Authority & State Power",
    189: "Foreign Policy & International Relations",
    190: "Government, Authority & State Power",
    191: "Government, Authority & State Power",
    192: "Government, Authority & State Power",
    193: "Government, Authority & State Power",
    194: "Government, Authority & State Power",
    195: "Government, Authority & State Power",
    196: "Government, Authority & State Power",
    197: "Government, Authority & State Power",
    198: "Government, Authority & State Power",
    199: "Government, Authority & State Power",
    200: "Government, Authority & State Power",
    201: "Government, Authority & State Power",
    202: "Government, Authority & State Power",
    203: "Government, Authority & State Power",
    204: "Government, Authority & State Power",
    205: "Immigration & National Identity",
    206: "Government, Authority & State Power",
    207: "Government, Authority & State Power",
    208: "Government, Authority & State Power",
    209: "Government, Authority & State Power",
    210: "Government, Authority & State Power",
    211: "Government, Authority & State Power",
    212: "Democracy & Political System",
    213: "Democracy & Political System",
    214: "Democracy & Political System",
    215: "Democracy & Political System",
    216: "Democracy & Political System",
    217: "Democracy & Political System",
    218: "Democracy & Political System",
    219: "Democracy & Political System",
    220: "Democracy & Political System",
    221: "Democracy & Political System",
    222: "Democracy & Political System",
    223: "Government, Authority & State Power",
    224: "Government, Authority & State Power",
    225: "Democracy & Political System",
    226: "Society & Culture",
    227: "Democracy & Political System",
    228: "Democracy & Political System",
    229: "Democracy & Political System",
    230: "Government, Authority & State Power",
    231: "Immigration & National Identity",
    232: "Foreign Policy & International Relations",
    233: "Foreign Policy & International Relations",
    234: "Foreign Policy & International Relations",
    235: "Foreign Policy & International Relations",
    236: "Foreign Policy & International Relations",
    237: "Foreign Policy & International Relations",
    238: "Foreign Policy & International Relations",
    239: "Foreign Policy & International Relations",
    240: "Immigration & National Identity",
    241: "Immigration & National Identity",
    242: "Foreign Policy & International Relations",
    243: "Immigration & National Identity",
    244: "Foreign Policy & International Relations",
    245: "Foreign Policy & International Relations",
    246: "Foreign Policy & International Relations",
    247: "Foreign Policy & International Relations",
    248: "Foreign Policy & International Relations",
    249: "Foreign Policy & International Relations",
    250: "Foreign Policy & International Relations",
    251: "Foreign Policy & International Relations",
    252: "Foreign Policy & International Relations",
    253: "Foreign Policy & International Relations",
    254: "Foreign Policy & International Relations",
    255: "Foreign Policy & International Relations",
    256: "Foreign Policy & International Relations",
    257: "Foreign Policy & International Relations",
    258: "Foreign Policy & International Relations",
    259: "Foreign Policy & International Relations",
    260: "Foreign Policy & International Relations",
    261: "Foreign Policy & International Relations",
    262: "Foreign Policy & International Relations",
    263: "Foreign Policy & International Relations",
    264: "Foreign Policy & International Relations",
    265: "Foreign Policy & International Relations",
    266: "Foreign Policy & International Relations",
    267: "Foreign Policy & International Relations",
    268: "Civil Liberties & Individual Rights",
    269: "Technology, Media & Privacy",
    270: "Justice, Crime & Law Enforcement",
    271: "Justice, Crime & Law Enforcement",
    272: "Justice, Crime & Law Enforcement",
    273: "Technology, Media & Privacy",
    274: "Technology, Media & Privacy",
    275: "Civil Liberties & Individual Rights",
    276: "Civil Liberties & Individual Rights",
    277: "Justice, Crime & Law Enforcement",
    278: "Civil Liberties & Individual Rights",
    279: "Civil Liberties & Individual Rights",
    280: "Family, Gender & Sexuality",
    281: "Justice, Crime & Law Enforcement",
    282: "Government, Authority & State Power",
    283: "Justice, Crime & Law Enforcement",
    284: "Justice, Crime & Law Enforcement",
    285: "Civil Liberties & Individual Rights",
    286: "Justice, Crime & Law Enforcement",
    287: "Civil Liberties & Individual Rights",
    288: "Economy & Markets",
    289: "Economy & Markets",
    290: "Economy & Markets",
    291: "Economy & Markets",
    292: "Economy & Markets",
    293: "Healthcare",
    294: "Society & Culture",
    295: "Economy & Markets",
    296: "Economy & Markets",
    297: "Economy & Markets",
    298: "Economy & Markets",
    299: "Economy & Markets",
    300: "Economy & Markets",
    301: "Economy & Markets",
    302: "Labor & Workers",
    303: "Economy & Markets",
    304: "Economy & Markets",
    305: "Economy & Markets",
    306: "Labor & Workers",
    307: "Religion & Morality",
    308: "Religion & Morality",
    309: "Religion & Morality",
    310: "Religion & Morality",
    311: "Religion & Morality",
    312: "Religion & Morality",
    313: "Religion & Morality",
    314: "Religion & Morality",
    315: "Religion & Morality",
    316: "Religion & Morality",
    317: "Religion & Morality",
    318: "Religion & Morality",
    319: "Religion & Morality",
    320: "Religion & Morality",
    321: "Religion & Morality",
    322: "Religion & Morality",
    323: "Religion & Morality",
    324: "Religion & Morality",
    325: "Religion & Morality",
    326: "Religion & Morality",
    327: "Technology, Media & Privacy",
    328: "Technology, Media & Privacy",
    329: "Technology, Media & Privacy",
    330: "Technology, Media & Privacy",
    331: "Technology, Media & Privacy",
    332: "Environment & Climate",
    333: "Technology, Media & Privacy",
    334: "Environment & Climate",
    335: "Technology, Media & Privacy",
    336: "Technology, Media & Privacy",
    337: "Society & Culture",
    338: "Healthcare",
    339: "Technology, Media & Privacy",
    340: "Society & Culture",
    341: "Immigration & National Identity",
    342: "Immigration & National Identity",
    343: "Immigration & National Identity",
    344: "Immigration & National Identity",
    345: "Immigration & National Identity",
    346: "Immigration & National Identity",
    347: "Immigration & National Identity",
    348: "Immigration & National Identity",
    349: "Immigration & National Identity",
    350: "Immigration & National Identity",
    351: "Immigration & National Identity",
    352: "Immigration & National Identity",
    353: "Immigration & National Identity",
    354: "Society & Culture",
    355: "Society & Culture",
    356: "Society & Culture",
    357: "Society & Culture",
    358: "Society & Culture",
    359: "Society & Culture",
    360: "Foreign Policy & International Relations",
    361: "Immigration & National Identity",
    362: "Immigration & National Identity",
    363: "Government, Authority & State Power",
    364: "Justice, Crime & Law Enforcement",
    365: "Civil Liberties & Individual Rights",
    366: "Technology, Media & Privacy",
    367: "Technology, Media & Privacy",
    368: "Civil Liberties & Individual Rights",
    369: "Government, Authority & State Power",
    370: "Religion & Morality",
    371: "Government, Authority & State Power",
    372: "Technology, Media & Privacy",
    373: "Civil Liberties & Individual Rights",
    374: "Government, Authority & State Power",
    375: "Government, Authority & State Power",
    376: "Democracy & Political System",
    377: "Democracy & Political System",
    378: "Economy & Markets",
    379: "Economy & Markets",
    380: "Economy & Markets",
    381: "Economy & Markets",
    382: "Healthcare",
    383: "Economy & Markets",
    384: "Economy & Markets",
    385: "Economy & Markets",
    386: "Economy & Markets",
    387: "Labor & Workers",
    388: "Labor & Workers",
    389: "Economy & Markets",
    390: "Labor & Workers",
    391: "Economy & Markets",
    392: "Taxation & Welfare",
    393: "Religion & Morality",
    394: "Religion & Morality",
    395: "Society & Culture",
    396: "Religion & Morality",
    397: "Religion & Morality",
    398: "Religion & Morality",
    399: "Religion & Morality",
    400: "Religion & Morality",
    401: "Religion & Morality",
    402: "Religion & Morality",
    403: "Religion & Morality",
    404: "Religion & Morality",
    405: "Society & Culture",
    406: "Religion & Morality",
    407: "Religion & Morality",
    408: "Immigration & National Identity",
    409: "Immigration & National Identity",
    410: "Society & Culture",
    411: "Immigration & National Identity",
    412: "Civil Liberties & Individual Rights",
    413: "Immigration & National Identity",
    414: "Immigration & National Identity",
    415: "Immigration & National Identity",
    416: "Society & Culture",
    417: "Society & Culture",
    418: "Immigration & National Identity",
    419: "Civil Liberties & Individual Rights",
    420: "Society & Culture",
    421: "Government, Authority & State Power",
    422: "Government, Authority & State Power",
    423: "Civil Liberties & Individual Rights",
    424: "Government, Authority & State Power",
    425: "Society & Culture",
    426: "Society & Culture",
    427: "Civil Liberties & Individual Rights",
    428: "Society & Culture",
    429: "Government, Authority & State Power",
    430: "Society & Culture",
    431: "Technology, Media & Privacy",
    432: "Society & Culture",
}

def main() -> int:
    items = json.loads(IN_FILE.read_text(encoding="utf-8"))
    if len(items) != len(CATEGORY_BY_INDEX):
        print(
            f"! Count mismatch: questions.json has {len(items)} items but "
            f"CATEGORY_BY_INDEX has {len(CATEGORY_BY_INDEX)} entries."
        )
        return 1

    buckets: dict[str, list[dict]] = {}
    for i, entry in enumerate(items):
        cat = CATEGORY_BY_INDEX.get(i, "Uncategorized")
        buckets.setdefault(cat, []).append(entry)

    order = CATEGORY_ORDER + ["Uncategorized"]

    lines: list[str] = []
    lines.append("# Questions to Review")
    lines.append("")
    lines.append(
        "Tick `[x]` on the questions you want to keep. Then run "
        "`extract_selected.py` to copy them into `FINAL QUESTIONS.md`."
    )
    lines.append("")
    lines.append(
        f"Total: **{len(items)} unique questions** across "
        f"**{len([c for c in order if c in buckets])} categories**."
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    total_check = 0
    for cat in order:
        if cat not in buckets:
            continue
        qs = buckets[cat]
        lines.append(f"## {cat} ({len(qs)})")
        lines.append("")
        for i, q in enumerate(qs, 1):
            text = q["text"].replace("\n", " ").strip()
            source = q.get("first_seen_in", "?")
            lines.append(f"- [ ] **{i}.** {text}  _(from: {source})_")
            total_check += 1
        lines.append("")

    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(HERE.parent)}")
    print(
        f"  {total_check} checkboxes across "
        f"{len([c for c in order if c in buckets])} categories"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
